<a href="https://colab.research.google.com/github/idoMadarr/Tensorflow-Deep-Learning/blob/main/the_basics/random_%26_shuffle_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import tensorflow as tf

random_1 = tf.random.Generator.from_seed(36)
random_1 = random_1.normal(shape=(6, 2))

random_2 = tf.random.Generator.from_seed(32)
random_2 = random_2.normal(shape=(4, 3))

random_3 = tf.random.Generator.from_seed(36)
random_3 = random_3.normal(shape=(6, 2))

print(random_1)
print(random_2)
print(random_3)

# Are they equal?
# If the base seed in the same and the shape is the same - YES!
print(random_1 == random_3)

tf.Tensor(
[[-0.645002    0.18022095]
 [-0.14656258  0.34374258]
 [ 0.41367555  0.17573498]
 [-1.0871261   0.45905176]
 [ 0.20386009  0.562024  ]
 [-2.3001142  -1.349454  ]], shape=(6, 2), dtype=float32)
tf.Tensor(
[[ 0.7901182   1.585549    0.4356279 ]
 [ 0.2364518  -0.1589871   1.302304  ]
 [ 0.9592239   0.85874265 -1.5181769 ]
 [ 1.4020647   1.5570306  -0.96762174]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[-0.645002    0.18022095]
 [-0.14656258  0.34374258]
 [ 0.41367555  0.17573498]
 [-1.0871261   0.45905176]
 [ 0.20386009  0.562024  ]
 [-2.3001142  -1.349454  ]], shape=(6, 2), dtype=float32)
tf.Tensor(
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]], shape=(6, 2), dtype=bool)


In [92]:
import tensorflow as tf

# Let say we want to feed our model/neural-network in images data for classification, it is wise to feed our model in unorder images.
# We want to avoid cases that we feed our model in just one item for long time - so we want to mix and shuffle the data.
# This approch is better for deep learning - beacuse we want to avoid constant pattern of learning.

# Shuffle a tensor (valueable when we want to shuffle our data)
not_shuffled = tf.constant([[1 ,2 ,3], [4, 5, 6], [7, 8, 9]])

print(not_shuffled)
print(not_shuffled.ndim)

# Shuffle our tensor
shuffled = tf.random.shuffle(not_shuffled)

# Keep in mind the the order of the values indide a specific array in not change
# what change is the order of the nested arrays itself
print(shuffled)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
2
tf.Tensor(
[[7 8 9]
 [1 2 3]
 [4 5 6]], shape=(3, 3), dtype=int32)


In [85]:
tf.random.set_seed(12) # Global seed
another_shuffled = tf.random.shuffle(not_shuffled, seed=12) # Operation seed

# NOTICE: If both global seed and operation seed are set, both seends are used in conjunction to determine the random sequence.
print(another_shuffled)

tf.Tensor(
[[7 8 9]
 [4 5 6]
 [1 2 3]], shape=(3, 3), dtype=int32)
