<a href="https://colab.research.google.com/github/idoMadarr/Tensorflow-Deep-Learning/blob/main/the_basics/constant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [15]:
# constant() is a way to build a scalar/vector/matrix/tensor. it's get only one properties that can be array or number

scalar = tf.constant(10)
print(scalar)
print("number of dimensions", scalar.ndim)

# Scalar is a unit that present a number (magnitude/size)
# Scalar has no shape(), Therefor ndim will be 0 (no dimension)

tf.Tensor(10, shape=(), dtype=int32)
number of dimensions 0


In [16]:
vector = tf.constant([5, 20, 10, 25])
print(vector)
print("number of dimensions", vector.ndim)

# Vector is a shape that present size & direction
# Vector contains only one array of numbers, Therefor ndim will be 1 (one dimension)

tf.Tensor([ 5 20 10 25], shape=(4,), dtype=int32)
number of dimensions 1


In [17]:
matrix = tf.constant([[5, 20, 10, 25], [1, 50, 10, 0]])
print(matrix)
print("number of dimensions", matrix.ndim)

# Matrix is a two-dimensional structure of numbers
# Matrix contain nested array, Therefor ndim will be 2

tf.Tensor(
[[ 5 20 10 25]
 [ 1 50 10  0]], shape=(2, 4), dtype=int32)
number of dimensions 2


In [22]:
matrix_ = tf.constant([[5, 20, 10], [1, 10, 0], [6, 12, 3], [4, 18, 9]])
print(matrix_)
print("number of dimensions", matrix_.ndim)

tf.Tensor(
[[ 5 20 10]
 [ 1 10  0]
 [ 6 12  3]
 [ 4 18  9]], shape=(4, 3), dtype=int32)
number of dimensions 2


In [26]:
tensor = tf.constant([
                        [[1, 2, 3], [4, 5, 6]],
                        [[7, 8, 9], [10, 11, 12]],
                        [[13, 14, 15], [16, 17, 18]]
                        ])
print(tensor)
print("number of dimensions", tensor.ndim)

# Tensor is a multi-dimensional array of numerical values that can be used to describe the physical state or properties of a material.
# Tensor contain multi-nested array, Therefor ndim will be x (3 and above)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
number of dimensions 3
