<a href="https://colab.research.google.com/github/idoMadarr/Tensorflow-Deep-Learning/blob/main/the_basics/4.other_ways_to_create_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

new_tensor = tf.ones([8, 3])
print(new_tensor)

other_tensor = tf.zeros([2 ,6])
another_tensor = tf.zeros(shape=(6, 2))

print(other_tensor)
print(another_tensor)



tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(8, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(2, 6), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]], shape=(6, 2), dtype=float32)


In [2]:
# Numpy Arrays vs Tensors
# The main difference between numpy arrays and tensor is that tensors can be run on GPU (super fast).

import numpy as np

numpy_A = np.arange(1, 61, dtype=np.int32) # -> 60 elements in total

print(numpy_A, "This is a simply numpy array")

# Turn Numpy arrays into a real tensor:

tensor_A = tf.constant(numpy_A)

print(tensor_A, "Real tensor - Vector")

# When we want to turn it into a multiy dimension tensor, the shape should be in accordance to the total numbers (which mean => shape(x * x * x) => total element (60)
A = tf.constant(numpy_A, shape=(3, 4, 5)) # 3 * 4 * 5 => 60
B = tf.constant(numpy_A, shape=(6, 10)) # 10 * 6 => 60

print(A, f"Dimention: {A.ndim}")
print(B, f"Dimention: {B.ndim}")



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60] This is a simply numpy array
tf.Tensor(
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60], shape=(60,), dtype=int32) Real tensor - Vector
tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]], shape=(3, 4, 5), dtype=int32) Dimention: 3
tf.Tensor(
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]], shape=(6, 10), dtype=int32) Dimention: 2
