In [ ]:
# Tensors has four main info attribute - Shape, Rank (ndim), Axis or Dimension & Size (total numbers in a tensor array)
import tensorflow as tf

In [2]:
rank_4_tensor = tf.zeros(shape=([2, 3, 4, 5]))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [3]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [14]:
print(rank_4_tensor.ndim, 'ndim')
print(tf.size(rank_4_tensor), 'size')
print(tf.size(rank_4_tensor).numpy(), 'size')
print(rank_4_tensor.dtype, 'dtype')
2 * 3 * 4 * 5
print(rank_4_tensor.shape)
print(rank_4_tensor.shape[0])
print(rank_4_tensor.shape[-1])

4 ndim
tf.Tensor(120, shape=(), dtype=int32) size
120 size
<dtype: 'float32'> dtype
(2, 3, 4, 5)
2
5


In [ ]:
# Tensor can be indexed just like python lists
# Get the first two element from every dimenstion
python_list = [1, 2, 3, 4, 5, 6]
print(python_list[:2])
print(rank_4_tensor[:2, :2, :2, :2])

[1, 2]
tf.Tensor(
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]], shape=(2, 2, 2, 2), dtype=float32)


In [19]:
# Get the first element from every dimenstion expect from the last dimenstion
print(rank_4_tensor[:1, :1, :1, :])

tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)
